server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zhou.springcloud.entities    # 所有Entity别名类所在包


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      #http://eureka7002.com:7002/eureka/
  instance:
    instance-id: cloud-payment-service8001
    prefer-ip-address: true #访问路径可以显示IP地址

